CREATE TABLE ${schema}.TB_USUARIO
(
    ID      UUID PRIMARY KEY,
    USUARIO VARCHAR(50)  NOT NULL,
    SENHA   VARCHAR(100) NOT NULL
);

CREATE TABLE ${schema}.TB_PESSOA
(
    ID              UUID PRIMARY KEY,
    NOME            VARCHAR(100) NOT NULL,
    DATA_NASCIMENTO DATE         NOT NULL,
    DOCUMENTO       VARCHAR(11)  NOT NULL,
    TELEFONE        VARCHAR(12)  NOT NULL,
    EMAIL           VARCHAR(50)  NOT NULL,
    TIPO            VARCHAR(20)  NOT NULL,
    ID_USUARIO      UUID,
    FOREIGN KEY (ID_USUARIO) REFERENCES ${schema}.TB_USUARIO
);

CREATE TABLE ${schema}.TB_PET
(
    ID              UUID PRIMARY KEY,
    NOME            VARCHAR(100)  NOT NULL,
    DATA_NASCIMENTO DATE          NOT NULL,
    RACA            VARCHAR(50)   NOT NULL,
    ESPECIE         VARCHAR(50)   NOT NULL,
    PESO            DECIMAL(4, 2) NOT NULL,
    ID_PESSOA       UUID          NOT NULL,
    FOREIGN KEY (ID_PESSOA) REFERENCES ${schema}.TB_PESSOA
);
